'use client';

import React, { useState } from 'react';
import { GENERATED_TESTS_CODE } from '@/services/MockBobService';
import { CheckCircle2, ChevronDown, ChevronUp, FileCode } from 'lucide-react';

export function GeneratedTestsViewer() {
  const [isOpen, setIsOpen] = useState(true);

  const testsList = [
    '✓ handles provider timeout gracefully',
    '✓ handles HTTP 500 error without leaking unhandled exceptions',
    '✓ handles malformed gateway response',
    '✓ handles missing transaction ID',
    '✓ preserves successful payment behavior for valid charges',
    '✓ prevents invalid order state on failure'
  ];

  return (
    <div className="bg-slate-950 border border-slate-800 rounded-lg p-4 font-mono space-y-3">
      <div
        onClick={() => setIsOpen(!isOpen)}
        className="flex items-center justify-between cursor-pointer select-none"
      >
        <div className="flex items-center gap-2">
          <FileCode className="w-4 h-4 text-purple-400" />
          <span className="text-xs font-bold text-slate-200">
            Regression Tests Generated by IBM Bob (6/6 Passing)
          </span>
        </div>
        {isOpen ? <ChevronUp className="w-4 h-4 text-slate-400" /> : <ChevronDown className="w-4 h-4 text-slate-400" />}
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
        {testsList.map((t, idx) => (
          <div key={idx} className="flex items-center gap-2 text-xs text-emerald-400 bg-emerald-500/10 px-2.5 py-1.5 rounded border border-emerald-500/20">
            <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400 flex-shrink-0" />
            <span>{t}</span>
          </div>
        ))}
      </div>

      {isOpen && (
        <div className="mt-3 pt-3 border-t border-slate-800">
          <div className="text-[11px] text-slate-400 mb-1">tests/payment.test.ts</div>
          <pre className="text-xs text-slate-300 bg-slate-900 p-3 rounded overflow-x-auto max-h-48">
            <code>{GENERATED_TESTS_CODE}</code>
          </pre>
        </div>
      )}
    </div>
  );
}
